[project]
name = "kitro-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Daniel Echevarria", email = "dan.echevarri@gmail.com" }]
requires-python = ">=3.13"
dependencies = [
    "faker>=40.37.0",
    "fastapi[standard]>=0.141.1",
    "psycopg[binary]>=3.3.5",
    "python-dotenv>=1.2.3",
    "sqlmodel>=0.0.42",
]


[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
